# What is the First Day of the Week?

Whether the Gregorian calendar shows Sunday or Monday as the first day of the week depends on where you live.

Do more countries start the week on Sunday or Monday? What about people? What about by continent?

The file `first-day-of-week.csv` shows the first day of the week for each territory. The file `population.csv` shows the population in the year 2020 for each territory in millions, and the file `four-regions.csv` specifies whether each territory is in asia, europe, africa, or the americas.

In [1]:
import pandas as pd
df = pd.read_csv('first-day-of-week.csv')
df.head()

        territory alpha3 first_day   units paper
0     Afghanistan    AFG       sat  metric    A4
1   Aland Islands    ALA       mon  metric    A4
2         Albania    ALB       mon  metric    A4
3         Algeria    DZA       sat  metric    A4
4  American Samoa    ASM       sun  metric    A4

In [2]:
pop = pd.read_csv('population.csv')
pop.head()

  alpha3  population
0    AFG       39.07
1    ALB        2.87
2    DZA       44.04
3    AND        0.08
4    AGO       33.45

In [4]:
regions = pd.read_csv('four-regions.csv')
regions.head()

  alpha3 four_regions
0    AUS         asia
1    BRN         asia
2    KHM         asia
3    CHN         asia
4    FJI         asia

### Project Ideas

- How many territories show Friday, Saturday, Sunday, and Monday as the `first_day` of the week?

- How many people start the week on Friday, Saturday, Sunday, and Monday?
	- Hint: This will involve a `merge`.

- Which of the `four_regions` predominantly start the week on Sunday? On Monday? Are there any regions that are more divided between Sunday and Monday?
	- Hint: This will also involve a `merge`.

In [5]:
# YOUR CODE HERE (add additional cells as needed)