- How many territories show Friday, Saturday, Sunday, and Monday as the `first_day` of the week?

In [140]:
import pandas as pd

df = pd.read_csv('first-day-of-week.csv')
df.head()

        territory alpha3 first_day   units paper
0     Afghanistan    AFG       sat  metric    A4
1   Aland Islands    ALA       mon  metric    A4
2         Albania    ALB       mon  metric    A4
3         Algeria    DZA       sat  metric    A4
4  American Samoa    ASM       sun  metric    A4

In [141]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 257 entries, 0 to 256
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   territory  257 non-null    object
 1   alpha3     254 non-null    object
 2   first_day  257 non-null    object
 3   units      257 non-null    object
 4   paper      257 non-null    object
dtypes: object(5)
memory usage: 10.2+ KB

In [142]:
df.head()

        territory alpha3 first_day   units paper
0     Afghanistan    AFG       sat  metric    A4
1   Aland Islands    ALA       mon  metric    A4
2         Albania    ALB       mon  metric    A4
3         Algeria    DZA       sat  metric    A4
4  American Samoa    ASM       sun  metric    A4

In [155]:
criteria = df['first_day'].isin(['fri', 'sat', 'sun', 'mon'])

In [168]:
df[criteria]

           territory alpha3 first_day   units paper  count
0        Afghanistan    AFG       sat  metric    A4    NaN
1      Aland Islands    ALA       mon  metric    A4    NaN
2            Albania    ALB       mon  metric    A4    NaN
3            Algeria    DZA       sat  metric    A4    NaN
4     American Samoa    ASM       sun  metric    A4    NaN
..               ...    ...       ...     ...   ...    ...
252  Wallis & Futuna    WLF       mon  metric    A4    NaN
253   Western Sahara    ESH       mon  metric    A4    NaN
254            Yemen    YEM       sun  metric    A4    NaN
255           Zambia    ZMB       mon  metric    A4    NaN
256         Zimbabwe    ZWE       sun  metric    A4    NaN

[254 rows x 6 columns]

In [169]:
df.drop(columns=['count'], inplace=True, axis=1)

In [186]:
df[df['territory'].str.startswith(('C'))]

                   territory alpha3 first_day   units      paper
38                  Cambodia    KHM       sun  metric         A4
39                  Cameroon    CMR       mon  metric         A4
40                    Canada    CAN       sun  metric  US-Letter
42                Cape Verde    CPV       mon  metric         A4
43     Caribbean Netherlands    BES       mon  metric         A4
44            Cayman Islands    CYM       mon      US         A4
45  Central African Republic    CAF       mon  metric         A4
47                      Chad    TCD       mon  metric         A4
48                     Chile    CHL       mon  metric  US-Letter
49                     China    CHN       mon  metric         A4
50          Christmas Island    CXR       mon  metric         A4
51         Clipperton Island    CPT       mon  metric         A4
52   Cocos (Keeling) Islands    CCK       mon  metric         A4
53                  Colombia    COL       sun  metric  US-Letter
54                   Comoros    COM       mon  metric         A4
55       Congo - Brazzaville    COG       mon  metric         A4
56          Congo - Kinshasa    COD       mon  metric         A4
57              Cook Islands    COK       mon  metric         A4
58                Costa Rica    CRI       mon  metric  US-Letter
59             Cote d’Ivoire    CIV       mon  metric         A4
60                   Croatia    HRV       mon  metric         A4
61                      Cuba    CUB       mon  metric         A4
62                   Curacao    CUW       mon  metric         A4
63                    Cyprus    CYP       mon  metric         A4
64                   Czechia    CZE       mon  metric         A4

In [231]:
new_criteria = df['first_day'].isin(['fri','sat','sun','mon'])

In [232]:
territory_counts = df[new_criteria].count().reset_index()

In [233]:
territory_counts.rename(columns={'index':'name', 0:'count'}, inplace=True)

In [235]:
territory_counts.iloc[0].reset_index().transpose()

               0      1
index       name  count
0      territory    254