In [1]:
import pandas as pd

df = pd.read_csv('largest-islands.csv')
df.head()

      region      island    area                countries    climate  rank
0     Africa  Madagascar  591896               Madagascar    tropics     4
1  Antarctic   Kerguelen    6200  Antarctic Lands, France  temperate    91
2       Asia       Sumba   11153                Indonesia    tropics    65
3       Asia      Hainan   34300                    China    tropics    37
4       Asia      Taiwan   36198                   Taiwan    tropics    36

- What islands are composed of multiple countries?
	- Hint: try `countries.str.contains(",")`

In [6]:
multi_counties = df.query('countries.str.contains(",")')[['island', 'countries']].sort_values(by='island')

In [8]:
multi_counties

                             island                    countries
23                           Borneo  Indonesia, Malaysia, Brunei
50                           Cyprus       Cyprus, United Kingdom
73                       Hispaniola    Dominican Republic, Haiti
45                          Ireland      Ireland, United Kingdom
98  Isla Grande de Tierra del Fuego             Chile, Argentina
1                         Kerguelen      Antarctic Lands, France
86                       New Guinea  Papua New Guinea, Indonesia