# Merge

In [3]:
import numpy as np
import pandas as pd

In [4]:
registrations = pd.DataFrame({'reg_id':[1,2,3,4],'name':['Andrew','Bobo','Claire','David']})
logins = pd.DataFrame({'log_id':[1,2,3,4],'name':['Xavier','Andrew','Yolanda','Bobo']})

In [5]:
registrations

   reg_id    name
0       1  Andrew
1       2    Bobo
2       3  Claire
3       4   David

In [6]:
logins

   log_id     name
0       1   Xavier
1       2   Andrew
2       3  Yolanda
3       4     Bobo

In [7]:
pd.merge(registrations, logins, on='name', how='inner')

   reg_id    name  log_id
0       1  Andrew       2
1       2    Bobo       4