In [3]:
import numpy as np
import pandas as pd

df = pd.read_csv("../../../../data/mpg.csv")

In [4]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino

In [5]:
df = df.drop(['name','horsepower'], axis=1)

In [6]:
df.columns

Index(['mpg', 'cylinders', 'displacement', 'weight', 'acceleration',
       'model_year', 'origin'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   weight        398 non-null    int64
 4   acceleration  398 non-null    float64
 5   model_year    398 non-null    int64
 6   origin        398 non-null    int64
dtypes: float64(3), int64(4)
memory usage: 21.9 KB

In [8]:
df.groupby(['model_year','cylinders']).mean().head()

                            mpg  displacement       weight  acceleration  \
model_year cylinders
70         4          25.285714    107.000000  2292.571429     16.000000
           6          20.500000    199.000000  2710.500000     15.500000
           8          14.111111    367.555556  3940.055556     11.194444
71         4          27.461538    101.846154  2056.384615     16.961538
           6          18.000000    243.375000  3171.875000     14.750000

                        origin
model_year cylinders
70         4          2.285714
           6          1.000000
           8          1.000000
71         4          1.923077
           6          1.000000

aggregate functions can work on single and multiple columns, and multiple functions for column selections use dict.

In [9]:
agg_df = df.aggregate({'weight':['mean','max'], 'mpg':['median','min']})

In [10]:
agg_df

             weight   mpg
mean    2970.424623   NaN
max     5140.000000   NaN
median          NaN  23.0
min             NaN   9.0

agg on groupby with one col selected

In [11]:
df.groupby(['model_year','cylinders'])['mpg'].agg(['mean','max','min','std','var'])

                           mean   max   min       std        var
model_year cylinders
70         4          25.285714  27.0  24.0  1.112697   1.238095
           6          20.500000  22.0  18.0  1.732051   3.000000
           8          14.111111  18.0   9.0  2.609685   6.810458
71         4          27.461538  35.0  22.0  3.502746  12.269231
           6          18.000000  19.0  16.0  1.069045   1.142857
           8          13.428571  14.0  12.0  0.786796   0.619048
72         3          19.000000  19.0  19.0       NaN        NaN
           4          23.428571  28.0  18.0  3.056249   9.340659
           8          13.615385  17.0  11.0  1.502135   2.256410
73         3          18.000000  18.0  18.0       NaN        NaN
           4          22.727273  29.0  19.0  3.319365  11.018182
           6          19.000000  23.0  16.0  2.203893   4.857143
           8          13.200000  16.0  11.0  1.361114   1.852632
74         4          27.800000  32.0  24.0  2.932576   8.600000
           6          17.857143  21.0  15.0  2.267787   5.142857
           8          14.200000  16.0  13.0  1.095445   1.200000
75         4          25.250000  33.0  22.0  3.333712  11.113636
           6          17.583333  21.0  15.0  2.020726   4.083333
           8          15.666667  20.0  13.0  2.422120   5.866667
76         4          26.766667  33.0  19.0  3.825976  14.638095
           6          20.000000  24.0  16.5  2.494438   6.222222
           8          14.666667  17.5  13.0  1.767767   3.125000
77         3          21.500000  21.5  21.5       NaN        NaN
           4          29.107143  36.0  21.5  4.039129  16.314560
           6          19.500000  22.0  17.5  1.767767   3.125000
           8          16.000000  17.5  15.0  0.845154   0.714286
78         4          29.576471  43.1  21.1  6.384799  40.765662
           5          20.300000  20.3  20.3       NaN        NaN
           6          19.066667  20.8  16.2  1.548802   2.398788
           8          19.050000  20.2  17.5  1.048332   1.099000
79         4          31.525000  37.3  22.3  4.349739  18.920227
           5          25.400000  25.4  25.4       NaN        NaN
           6          22.950000  28.8  19.8  3.851104  14.831000
           8          18.630000  23.9  15.5  2.757636   7.604556
80         3          23.700000  23.7  23.7       NaN        NaN
           4          34.612000  46.6  23.6  6.597621  43.528600
           5          36.400000  36.4  36.4       NaN        NaN
           6          25.900000  32.7  19.1  9.616652  92.480000
81         4          32.814286  39.1  25.8  3.844904  14.783286
           6          23.428571  30.7  17.6  4.139531  17.135714
           8          26.600000  26.6  26.6       NaN        NaN
82         4          32.071429  44.0  23.0  5.054727  25.550265
           6          28.333333  38.0  22.0  8.504901  72.333333

abbreviated agg() of aggregation() use [] for function applied for entire df

In [16]:
df.agg(['std','mean','max','min','var']).transpose()

                     std         mean     max     min            var
mpg             7.815984    23.514573    46.6     9.0      61.089611
cylinders       1.701004     5.454774     8.0     3.0       2.893415
displacement  104.269838   193.425879   455.0    68.0   10872.199152
weight        846.841774  2970.424623  5140.0  1613.0  717140.990526
acceleration    2.757689    15.568090    24.8     8.0       7.604848
model_year      3.697627    76.010050    82.0    70.0      13.672443
origin          0.802055     1.572864     3.0     1.0       0.643292

In [20]:
df.agg(['std','mean','max','min','var'])[['mpg','displacement','weight']].transpose()

                     std         mean     max     min            var
mpg             7.815984    23.514573    46.6     9.0      61.089611
displacement  104.269838   193.425879   455.0    68.0   10872.199152
weight        846.841774  2970.424623  5140.0  1613.0  717140.990526